[uv]
# Use the latest version of uv
version = "0.1.0"

[uv.publish]
# Configure publishing options
repository = "pypi"

[uv.dev-dependencies]
# Development dependencies
pytest = ">=7.0.0"
pytest-cov = ">=4.0.0"
black = ">=23.0.0"
isort = ">=5.0.0"
